export const PERMISSIONS = {
    USER_MANAGE: 'USER_MANAGE',

    PRODUCT_CREATE: 'PRODUCT_CREATE',
    PRODUCT_UPDATE: 'PRODUCT_UPDATE',
    PRODUCT_DELETE: 'PRODUCT_DELETE',
    PRODUCT_VIEW: 'PRODUCT_VIEW',

    PURCHASE_CREATE: 'PURCHASE_CREATE',
    PURCHASE_VIEW: 'PURCHASE_VIEW',

    STOCK_ADJUST: 'STOCK_ADJUST',
    STOCK_VIEW: 'STOCK_VIEW',

    INVOICE_CREATE: 'INVOICE_CREATE',
    INVOICE_CANCEL: 'INVOICE_CANCEL',
    INVOICE_VIEW: 'INVOICE_VIEW',

    REPORT_VIEW: 'REPORT_VIEW',
} as const;
