export const DEFAULT_BRANCH_SETTINGS = {
    timezone: 'Asia/Karachi',
    currency: 'PKR',
    print_logo: true,
    print_tax_number: true,
    print_phone: true,
    print_address: true,
    print_qr_code: false,
    show_cashier_name: true,
    minimum_stock_quantity: 10,
    critical_stock_quantity: 5,
    expiry_alert_before_days: 30,
    enable_stock_sharing: false,
    share_inventory_details: false,
    allow_reservations: false,
    search_radius: 1.0,
    radius_unit: 'KM' as const,
    email_notifications: true,
    sms_notifications: false,
    push_notifications: true,
    in_app_notifications: true,
    low_stock_alert: true,
    expiry_alert: true,
    purchase_alert: true,
    sale_alert: false,
};
